### ISSUE TITLE
Incompatiblity with Bountiful mod (forge)

### ISSUE THREAD

**Issue by Cixon** [tr7zw/TRansliterationLib#7]
**Context:** Creating a mod-pack and would love to utilize not enough animations mod but because it uses a interesting dependency such as TRansliterationlib, it conflicts with one of the mods I love to use.

### Link to Github & Logs:
https://github.com/ejektaflex/Bountiful/issues/114

### Link to mods used:
[Bountiful v3.3.0](https://www.curseforge.com/minecraft/mc-mods/bountiful/files/3183049)
[Kotlin for Forge (dependency)](https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge/files/3143223)

**Comment by tr7zw** [comment]
I have a guess what happened there, I'll check it and push a fix tomorrow

**Comment by Cixon** [comment]
> 
> 
> I have a guess what happened there, I'll check it and push a fix tomorrow

Sweet! Thank you.

**Comment by tr7zw** [comment]
Huh I installed it and there is no issue? Can you post a full list of the other installed mods?

**Comment by Cixon** [comment]
I can but I utilize a modpack. It would be a pain to go through 40+ mods.

**Comment by tr7zw** [comment]
If it's a public modpack then link that, or a screenshot of the mods folder with all mods should do too.

**Comment by tr7zw** [comment]
Also I've uploaded a 1.0.1 release that fixes what I think might be the issue. Please test with that :).

**Comment by Cixon** [comment]
> 
> 
> Also I've uploaded a 1.0.1 release that fixes what I think might be the issue. Please test with that :).

This fixed the issue !
Thanks !

**Comment by tr7zw** [comment]
Yea a class that I used during development for testing because of an issue getting into the final build, causing issues when signed jars were required because it tried to overwrite a forge class. Removing it did the trick (it wasn't incompatible with any mod, but with certain forge environments, probably why I wasn't able to recreate it/catch it before release).

**Comment by Cixon** [comment]
> 
> 
> Yea a class that I used during development for testing because of an issue getting into the final build, causing issues when signed jars were required because it tried to overwrite a forge class. Removing it did the trick (it wasn't incompatible with any mod, but with certain forge environments, probably why I wasn't able to recreate it/catch it before release).

Just happy I was able to help!
