### ISSUE TITLE
Giving crash with Sodium mod

### ISSUE THREAD

**Issue by Aryangpt007** [tr7zw/TRansliterationLib#79]
[crash-2021-09-30_17.32.04-client.txt](https://github.com/tr7zw/TRansliterationLib/files/7260717/crash-2021-09-30_17.32.04-client.txt)
This is the crash report i recieve on startup

**Comment by tr7zw** [comment]
Hm this is a really odd crash. Can you verify that not having TRansliterationlib(and the mods that need it Nea/firstperson) does not cause this crash?

**Comment by Aryangpt007** [comment]
ah yes its not related to Transliterationlib, I apologize for the trouble, i found the reason why it was not working, one of the mods packaged sodium inside their own jar files and then when i added it myself it caused a crash. i overlooked that mod since it was not mentioned in modpack. Thank you anyway for taking the time to look at my issue.
