### ISSUE TITLE
Issue with modpack

### ISSUE THREAD

**Issue by Assasingus14** [tr7zw/TRansliterationLib#80]
I got this crash log indicating transliteration is the issue. dunno what seems to be triggering it though

[crash-2021-10-03_18.58.25-client.txt](https://github.com/tr7zw/TRansliterationLib/files/7275030/crash-2021-10-03_18.58.25-client.txt)

**Comment by tr7zw** [comment]
Seems to be an issue with colored_lights and sodium?
From what I can tell this mod tries to access a class that both colored lights and sodium modify in an incompatible way.

**Comment by tr7zw** [comment]
Since there is no further feedback, I'll assume that this is resolved.
