### ISSUE TITLE
Unable to load in LoliServer.

### ISSUE THREAD

**Issue by FireTomcat** [tr7zw/TRansliterationLib#82]
I tried to load in Forge and Spigot servers, but failed. Error message:Details:
	Mod File: TRansliterationLib-1.0.4.jar
	Failure message: TRansliterationLib Mod (transliterationlib) has failed to load correctly
		java.lang.RuntimeException: Attempted to load class net/minecraft/client/renderer/RenderType for invalid dist DEDICATED_SERVER
	Mod Version: 1.0.4
	Mod Issue URL: https://github.com/tr7zw/TRansliterationLib/issues
	Exception message: java.lang.RuntimeException: Attempted to load class net/minecraft/client/renderer/RenderType for invalid dist DEDICATED_SERVER
(The game version is 1.16.5)

**Comment by tr7zw** [comment]
This is a client mod.
