### ISSUE TITLE
Issue with "TRansliterationLib mod has failed to load correctly" when running some mods.

### ISSUE THREAD

**Issue by Swiftbed** [tr7zw/TRansliterationLib#83]
So look, not gonna tell ya too much, just the things.
When I tried to run NotEnoughAnimations and FirstPersonMod - apparently TRansliterationLib can't "START_RENDER" or smh like that. It just says

"Failed to create mod instance. ModID: transliterationlib, class dev.tr7zw.transliterationlib.forge.TRansliterationLibMod
java.lang.NoSuchFieldError: START_RENDER"

That's all.

Here's some stuff. (It's 1.16.5. I'm using 1.0.2, but same stuff happened on 1.0.4) 

[forge error screen] https://user-images.githubusercontent.com/69075215/136696436-00840596-66fe-4d95-ae12-ed75c0d8dadb.png

[crash-2021-10-10_15.39.48-fml.txt] (https://github.com/tr7zw/TRansliterationLib/files/7317427/crash-2021-10-10_15.39.48-fml.txt

[latest.log] (https://github.com/tr7zw/TRansliterationLib/files/7317429/latest.log)

Anyways, if you do, thanks for noticing and helping!

**Comment by tr7zw** [comment]
Update to 1.0.4.
