### ISSUE TITLE
Your library is attempting to modify a signed JAR

### ISSUE THREAD

**Issue by ChloeDawn** [tr7zw/TRansliterationLib#9]
`java.lang.SecurityException: class "net.minecraftforge.fml.common.Mod"'s signer information does not match signer information of other classes in the same package`

**Comment by ChloeDawn** [comment]
If what you need is Forge, you can just add it as a dependency from the maven...

```groovy
repositories {
  maven { url 'https://files.minecraftforge.net/maven' }
}
```
```groovy
compileOnly 'net.minecraftforge:forge:1.16.5-36.0.13:universal'
```

**Comment by tr7zw** [comment]
Yea there was an issue when trying to get forge from their maven repo using maven(for the mods that build on this), and this stupid hack kinda accidentally ended up in the release jar. Just put out a 1.0.1 release that removes the Mod file to hopefully fix the random crashes people experience.
